In [10]:
import pickle

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()

from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, Bidirectional

In [8]:
# Load in the training set
training_set = pd.read_csv("data/mini_data/data/training_set/log_mini.csv")
training_set.hist_user_behavior_reason_start = training_set.hist_user_behavior_reason_start.astype('category')
training_set.hist_user_behavior_reason_end = training_set.hist_user_behavior_reason_end.astype('category')
training_set.context_type = training_set.context_type.astype('category')
training_set.date = training_set.date.apply(pd.to_datetime)

# Load in the track features
track_data = pd.read_pickle("data/pickles/track_features.pkl")

# Using skip_2 as the ground truth
training_set['skipped'] = (training_set.skip_2 | training_set.skip_1).astype('int32')
training_set = training_set.drop(columns=['skip_1','skip_2','skip_3','not_skipped'])
track_data.iloc[:,1:] = track_data.iloc[:,1:].astype('float32')

training_set.head()

session_id  ...  skipped
0  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...        0
1  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...        0
2  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...        0
3  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...        0
4  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...        0

[5 rows x 18 columns]

In [9]:
track_data.head()

track_id  ...  acoustic_vector_7
0  t_a540e552-16d4-42f8-a185-232bd650ea7d  ...          -0.675907
1  t_67965da0-132b-4b1e-8a69-0ef99b32287c  ...          -0.525795
2  t_0614ecd3-a7d5-40a1-816e-156d5872a467  ...          -0.433496
3  t_070a63a0-744a-434e-9913-a97b02926a29  ...          -0.542753
4  t_d6990e17-9c31-4b01-8559-47d9ce476df1  ...          -0.455496

[5 rows x 30 columns]

In [27]:
# Merge the dataframes
full_data = training_set.merge(
    track_data,
    left_on='track_id_clean',
    right_on='track_id'
).drop(
    columns=["track_id_clean","track_id"]
)

# Convert column types
category_columns = [
    'context_type',
    'hist_user_behavior_reason_start',
    'hist_user_behavior_reason_end'
]
full_data = pd.get_dummies(full_data,columns=category_columns,drop_first=True)
full_data.date = full_data.date.astype('int')
full_data.iloc[:,1:] = full_data.iloc[:,1:].astype('float32')

full_data.head()

session_id  ...  hist_user_behavior_reason_end_trackdone
0  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
1  0_00079a23-1600-486a-91bd-5208be0c745a  ...                                      0.0
2  0_012b0fb4-0cc3-429f-9a78-cc6e622153fb  ...                                      1.0
3  0_013cc010-c476-4ad2-8972-73449e0b2ef4  ...                                      1.0
4  0_01a5f0dc-9938-48c9-92f1-c7e51f34d290  ...                                      0.0

[5 rows x 62 columns]

In [28]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 167880 entries, 0 to 167879
Data columns (total 62 columns):
session_id                                    167880 non-null object
session_position                              167880 non-null float32
session_length                                167880 non-null float32
context_switch                                167880 non-null float32
no_pause_before_play                          167880 non-null float32
short_pause_before_play                       167880 non-null float32
long_pause_before_play                        167880 non-null float32
hist_user_behavior_n_seekfwd                  167880 non-null float32
hist_user_behavior_n_seekback                 167880 non-null float32
hist_user_behavior_is_shuffle                 167880 non-null float32
hour_of_day                                   167880 non-null float32
date                                          167880 non-null float32
premium                                       1678

In [33]:
print("Number of unique sessions: %d" % full_data.session_id.unique().shape)

Number of unique sessions: 10000


In [41]:
full_data.groupby('session_id').session_position.max().value_counts()

20.0    5066
10.0     819
11.0     752
12.0     646
13.0     547
14.0     459
15.0     435
16.0     339
17.0     320
19.0     314
18.0     303
Name: session_position, dtype: int64

In [38]:
session_lengths = full_data.groupby('session_id').session_position.max()
sessions_full_length = session_lengths == 20
full_data_s20 = full_data[[]]

20.0    5066
10.0     819
11.0     752
12.0     646
13.0     547
14.0     459
15.0     435
16.0     339
17.0     320
19.0     314
18.0     303
Name: session_position, dtype: int64

In [61]:
session_lengths = full_data.groupby('session_id').session_position.max().reset_index()
full_length_session_ids = session_lengths[session_lengths.session_position == 20].session_id.values
"0_00006f66-33e5-4de7-a324-2d18e439fc1e" in full_length_session_ids

True

In [66]:
full_data_subset = full_data[pd.Series([(i in full_length_session_ids) for i in full_data.session_id])].reset_index(drop=True)
full_data_subset.head(10)

session_id  ...  hist_user_behavior_reason_end_trackdone
0  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
1  0_012b0fb4-0cc3-429f-9a78-cc6e622153fb  ...                                      1.0
2  0_01f86af2-cf48-42a6-9bf8-adb91f072909  ...                                      0.0
3  0_02340c3b-c370-4c98-b759-87be85e11aa3  ...                                      0.0
4  0_02a8ebbd-5a12-4343-a7da-2ea912102f90  ...                                      0.0
5  0_04ab5699-1f6a-40ef-b8a6-9ebad09e85f6  ...                                      0.0
6  0_05219b57-68f2-4eac-a139-85cef6f3809b  ...                                      1.0
7  0_05b0cc6b-6615-44bd-ba6d-d6737cd5324a  ...                                      0.0
8  0_06a28c80-2dca-434d-8404-3a86f77a0a10  ...                                      0.0
9  0_0792cde4-90a0-45e9-bf9e-b4f78114f1bf  ...                                      0.0

[10 rows x 62 columns]

In [87]:
full_data_subset = full_data_subset.sort_values(["session_id",'session_position']).reset_index(drop=True)
full_data_subset.head(30)

session_id  ...  hist_user_behavior_reason_end_trackdone
0   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
1   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
2   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
3   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
4   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
5   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
6   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
7   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
8   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
9   0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
10  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
11  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
12  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
13  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      1.0
14  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
15  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
16  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
17  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
18  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
19  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                                      0.0
20  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
21  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
22  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
23  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
24  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
25  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
26  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
27  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
28  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0
29  0_0000a72b-09ac-412f-b452-9b9e79bded8f  ...                                      0.0

[30 rows x 62 columns]

In [81]:
full_data_subset.shape

(101320, 62)

In [91]:
X = full_data_subset.drop(columns=['session_id','skipped']).values.reshape((-1,20,full_data_subset.shape[-1]-2))
y = full_data_subset.skipped.values.reshape((-1,20,1))
X.shape, y.shape

((5066, 20, 60), (5066, 20, 1))

In [95]:
X[0]

array([[ 1., 20.,  0., ...,  0.,  0.,  1.],
       [ 2., 20.,  0., ...,  0.,  0.,  1.],
       [ 3., 20.,  0., ...,  0.,  0.,  1.],
       ...,
       [18., 20.,  0., ...,  0.,  0.,  0.],
       [19., 20.,  0., ...,  0.,  0.,  0.],
       [20., 20.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [113]:
y[0]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [114]:
full_data_subset.shape[0] * 20

2026400

In [115]:
X2 = []
y2 = []
for i in range(X.shape[0]):
    for j in range(-1,-21,-1):
        X2.append(np.concatenate((X[i,j:,:],np.zeros((20+j,60)))))
        y2.append(np.concatenate((y[i,j:,:],np.zeros((20+j,1)))))
X2 = np.array(X2)
y2 = np.array(y2)
X2.shape, y2.shape

((101320, 20, 60), (101320, 20, 1))

In [123]:
X[0]

array([[ 1., 20.,  0., ...,  0.,  0.,  1.],
       [ 2., 20.,  0., ...,  0.,  0.,  1.],
       [ 3., 20.,  0., ...,  0.,  0.,  1.],
       ...,
       [18., 20.,  0., ...,  0.,  0.,  0.],
       [19., 20.,  0., ...,  0.,  0.,  0.],
       [20., 20.,  0., ...,  0.,  0.,  0.]], dtype=float32)

***

Now let's create the model that we'll be training

In [ ]:
def build_model():
    m = Sequential()